version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - yum update -y
      - mkdir -p ~/.docker
      - echo -n "$DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD" | base64 -w 0 > docker-auth.txt
      - echo -n '{"auths":{"https://index.docker.io/v1/":{"auth":"'$(cat docker-auth.txt)'","email":"rachiddichar90@gmail.com"}}}' > ~/.docker/config.json
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - aws configure list
      - echo "Kubeconfig file contents:"
      - aws eks update-kubeconfig --region us-east-1 --name Flask-cluster
      - cat ~/.kube/config
      - kubectl config view

  build:
    commands:
      - git clone https://github.com/sabouf1/AWS-Serverless-Mini-Project
      - cd AWS-Serverless-Mini-Project
      - docker build -t thedictator10/flask-app:latest .
      - echo Docker image built successfully.
      - docker push thedictator10/flask-app:latest
      - kubectl delete deployment flask-app-deployment
      - kubectl apply -f flask-app-deployment.yaml
      # - kubectl apply -f flask-app-service.yaml
      - kubectl get services
