version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - yum update -y
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - aws eks update-kubeconfig --region us-east-1 --name Flask-cluster
  build:
    commands:
      - git clone https://github.com/sabouf1/AWS-Serverless-Mini-Project
      - cd AWS-Serverless-Mini-Project
      - kubectl apply -f flask-app-deployment.yaml
      - kubectl apply -f flask-app-service.yaml
